///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String astronaut = 'assets/3d_models/astronaut/astronaut.obj';
  static const String image1 = 'assets/images/image1.jpeg';
  static const String image2 = 'assets/images/image2.jpeg';
  static const String image3 = 'assets/images/image3.jpeg';
  static const String logo = 'assets/images/logo.jpg';
  static const String requestError = 'assets/images/request_error.png';
  static const String turnDigitalSplash = 'assets/flares/turn_digital_splash.flr';

}
